---
- name: Database
  become: true
  become_user: postgres
  postgresql_db:
    name: decide19

- name: Database user
  become: true
  become_user: postgres
  postgresql_user:
    encrypted: yes
    db: decide19
    name: decide
    password: decide
    priv: ALL

