# Generated by Django 2.0 on 2022-12-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='already_voted',
            field=models.BooleanField(default=False),
        ),
    ]
